### ISSUE TITLE
.NET Client

### ISSUE THREAD

**Issue by weitzhandler** [garethrbrown/aspnet-signalr-upload-progress-bar#3]
Hi,

First of all, I'd like to thank you for sharing this awesome utility.

In my scenario, the client is a C# WPF app, and the server an ASP.NET Core one.

- Can I declare the upload as a controller action?
- What do I pass from the client side using `HttpClient`?

**Comment by gbro3n** [comment]
Closing as old. Sorry for not getting to this sooner!
